<?xml version="1.0"?>
<package format="3">
  <name>tb3_trajectory_following</name>
  <version>1.0.0</version>
  <description>TurtleBot3 Pure Pursuit Trajectory Tracking</description>
  <maintainer email="student@example.com">Student</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
